# Generated by Django 5.0.6 on 2024-05-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_profile_city_alter_profile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='address',
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
