# Generated by Django 5.0.6 on 2024-05-29 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_profile_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mobile_number',
        ),
    ]
