# Generated by Django 5.0.6 on 2024-05-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_profile_email_alter_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(default='Unknown', max_length=15),
            preserve_default=False,
        ),
    ]
