# Generated by Django 4.2.4 on 2024-06-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default='Unknown', max_length=255, null=True),
        ),
    ]
